wandb_version: 1

architecture:
  desc: null
  value: BERT(Restructured)
dataset:
  desc: null
  value: CoLA
epochs:
  desc: null
  value: 6
_wandb:
  desc: null
  value:
    python_version: 3.9.13
    cli_version: 0.16.4
    framework: huggingface
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1711375444.0
    t:
      1:
      - 1
      - 5
      - 49
      - 51
      - 53
      - 55
      2:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.9.13
      5: 0.16.4
      8:
      - 3
      - 5
      13: windows-amd64
